spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/operations_hub
    username: operations_user
    password: operations_pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
