spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Sync_pafproject
    username: campus_user
    password: sync
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
